services:
  5gc:
    container_name: open5gs_5gc
    build:
      context: open5gs
      target: open5gs
      args:
        OS_VERSION: "22.04"
        OPEN5GS_VERSION: "v2.7.0"
    env_file:
      - ${OPEN_5GS_ENV_FILE:-open5gs/open5gs.env} # Asegúrate de que este archivo configure MCC=001, MNC=01, TAC=7
    privileged: true
    ports:
      - "9898:9999/tcp"
    command: 5gc -c open5gs-5gc.yml
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.20 7777" ]
      interval: 3s
      timeout: 1s
      retries: 60
    networks:
      ran:
        ipv4_address: 10.53.1.2 # IP estática para el 5GC

  gnb:
    container_name: srsran_gnb
    image: srsran/gnb
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    privileged: true
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - /usr/share/uhd/images:/usr/share/uhd/images
      - gnb-storage:/tmp
    configs:
      - gnb_config.yml
      - gnb_compose_config.yml
    networks:
      ran:
        ipv4_address: 10.53.1.3 # IP estática para el gNB
      metrics:
        ipv4_address: 172.19.1.3
    depends_on:
      5gc:
        condition: service_healthy
    command: gnb -c /gnb_config.yml -c /gnb_compose_config.yml

  ue:
    container_name: srsran_ue
    image: srsran/ue # Asume que tienes una imagen srsran/ue disponible o la construirás
    build:
      context: ..
      dockerfile: docker/Dockerfile.ue # Si necesitas construir el UE desde el código fuente
      args:
        OS_VERSION: "24.04"
    privileged: true
    cap_add:
      - SYS_NICE
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - ue-storage:/tmp
    configs:
      - ue_config.conf
    networks:
      ran:
        ipv4_address: 10.53.1.4 # IP estática para el UE
    depends_on:
      gnb:
        condition: service_healthy
    command: ue -c /ue_config.conf

configs:
  gnb_config.yml:
    file: ./gnb.yml # Ruta al archivo de configuración del gNB generado
  gnb_compose_config.yml:
    content: |
      cu_cp:
        amf:
          addr: 10.53.1.2 # IP del 5GC
          bind_addr: 10.53.1.3 # IP del gNB
      metrics:
        autostart_stdout_metrics: true
        enable_json: true
      remote_control:
        bind_addr: 0.0.0.0
        enabled: true
  ue_config.conf:
    file: ./ue.conf # Ruta al archivo de configuración del UE generado

volumes:
  gnb-storage:
  ue-storage:

networks:
  ran:
    ipam:
      driver: default
      config:
        - subnet: 10.53.1.0/24
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24